site_name: Demonstrator Docs


theme:
  name: "material"
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/Hergoss/AUT_demonstrator.git

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [code]
          options:
            docstring_style: google
            show_source: true
  - mkdocs-video:
      is_video: True
      video_controls: True
      video_muted: False
      css_style:
        width: "100%"
        height: "auto"

nav:
  - Overview: index.md
  - Setup Guide: setup.md
  - Usage Guide: user_guide.md
  - Augmentation Guide: augmentation.md
  - Training Guide: training.md
  - Streamlit Guide: streamlit.md
  - Documentation Guide: documentation.md
  - Contact: contact.md