site_name: Demonstrator Docs


theme:
  name: "material"
  icon:
    repo: fontawesome/brands/gitlab
repo_url: https://git.tu-berlin.de/henrik.he/demo_augmentation.git

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true

nav:
  - Overview: index.md
  - Setup Guide: setup.md
  - Usage Guide: user_guide.md
  - Augmentation Guide: augmentation.md
  - Training Guide: training.md
  - Streamlit Guide: streamlit.md
  - Documentation Guide: documentation.md
  - Contact: contact.md